#!/bin/bash

# assemble apu, compile test, and link.
# two links - test with apu, and test without apu.

m80 =am9511/L
m80 =apu/L
f80 =test/L

lib apu=am9511,apu/E

l80 test,noapu/N/Y/E
l80 test,apu,apu/N/Y/E
